<script lang="ts">
	import type { CardRationale } from '$lib/models/Card';
	import { formatDate } from '$lib/utils/date';

	interface Props {
		rationale: CardRationale;
	}

	const { rationale }: Props = $props();
</script>

<p class="text">{rationale.text}</p>

{#if rationale.aiModel}
	<p class="disclaimer">
		This summary was generated by {rationale.aiModel} on {formatDate(
			new Date(rationale.dateUpdated)
		)}.
		{#if rationale.dateApproved}
			It was manually reviewed and approved by a human editor on {formatDate(
				new Date(rationale.dateApproved)
			)}.
		{:else}
			It has not yet been reviewed by a human editor and may be inaccurate.
		{/if}
		<a href="/ai-rationales">Learn more.</a>
	</p>
{/if}

<style lang="scss">
	.text {
		white-space: pre-line;
	}

	.disclaimer {
		font-size: 0.8em;
		font-style: italic;
		opacity: 0.7;
	}
</style>
