<script lang="ts">
	import type { CardRationale } from '$lib/models/Card';
	import { formatDate } from '$lib/utils/date';
	import { needsRationaleReview } from '$lib/utils/rationale';
	import RationaleVoting from './RationaleVoting.svelte';

	interface Props {
		scryfallId: string;
		rationale: CardRationale;
		voteToken: string | null;
	}

	const { scryfallId, rationale, voteToken }: Props = $props();

	const needsReview = $derived(needsRationaleReview(rationale));
</script>

<p class="text">{rationale.text}</p>

{#if rationale.aiModel}
	<p class="disclaimer">
		This summary was generated by {rationale.aiModel} on {formatDate(
			new Date(rationale.dateUpdated)
		)}.
		{#if rationale.dateApproved}
			It was manually reviewed and approved by a human editor on {formatDate(
				new Date(rationale.dateApproved)
			)}.
		{:else}
			It has not yet been reviewed by a human editor and may contain some inaccuracies.
		{/if}
		<a href="/ai-rationales">Learn more.</a>
	</p>
{/if}

{#if needsReview && voteToken}
	<RationaleVoting {scryfallId} {voteToken} />
{/if}

<style lang="scss">
	.text {
		white-space: pre-line;
	}

	.disclaimer {
		font-size: 0.8em;
		font-style: italic;
		opacity: 0.7;
	}
</style>
